@startuml
'https://plantuml.com/sequence-diagram

title High Level Gamepad Walking

activate GamePadBehaviorController
activate MotionController
activate Structure

[o-> GamePadBehaviorController: Start()
loop
GamePadBehaviorController -> GamePadBehaviorController: GetMoveInput() -> Twist
GamePadBehaviorController -> GamePadBehaviorController: GetOffsetInput() -> Twist
GamePadBehaviorController -> GamePadBehaviorController: GetOffsetInput() -> Twist
GamePadBehaviorController -> MotionController: MoveThorax(Twist)
MotionController -> Structure: SetPosture(Posture)
MotionController -> Structure: GetPosture()
return Posture
GamePadBehaviorController -> GamePadBehaviorController: Spin()
end


@enduml
